### ISSUE TITLE
Unable to load addon script

### ISSUE THREAD

**Issue by axvemi** [eskandrej/Minstance#5]
Hi!

Trying to import the addon (downloading it as a ZIP since there is no official releases) and I'm getting this error when trying to enable it:

![image](https://user-images.githubusercontent.com/95682085/219886255-fb36ec82-6057-49fb-a315-0ceef375d61b.png)

I`m using Godot 4.0 RC2

**Comment by eskandrej** [comment]
Sorry, I forgot to mention that plugin is for Godot 3.5.1. I'm working on porting to version 4.

**Comment by axvemi** [comment]
Oh just saw this.

Created this pull request with some updates. It's not complete yet but maybe it can help you a bit: https://github.com/eskandrej/Minstance/pull/6
